### ISSUE TITLE
Errors in data-type-assignment.js

### ISSUE THREAD

**Issue by Ahuoyiza** [teetia1/7-days-of-js#1]
# Errors in data-type-assignment.js submission 
File: [data-type-assignment](https://github.com/teetia1/7-days-of-js/blob/main/data-type-assignment.js)

### Task 1:
Try running the codes to see what it actually logs in the console, the answers submitted aren't correct

Format error in line 7 
I will post the original code here for reference:

let userName = "Sophia";

console. log( `hello ${3}` );  //?

console.log( `hello ${"userName"}` ); //?

alert( `hello ${userName}` ); // ?

### Task 2:
Good execution , however use the console.log(typeof price) to see the actual data type of the variable price.
others are correct

**Comment by teetia1** [comment]
1. I changed the single quotation marks in line 2, 7 and 10 to back ticks.
2. Which prompted a new output as such I changed the output as required.
3. In task 2 I used console.log(typeof price); to determine the typeof() "price" value and changed the answer appropriately.

**Comment by Ahuoyiza** [comment]
👏👏👏👏
